export const GET_RESTRAUNT_LIST = "GET_RESTRAUNT_LIST"
export const GET_RESTRAUNT_LIST_ERROR = "GET_RESTRAUNT_LIST_ERROR"
export const GET_RESTRAUNT_LIST_SUCCESS = "GET_RESTRAUNT_LIST_SUCCESS"
export const GET_IMAGE_LIST = "GET_IMAGE_LIST"
export const GET_IMAGE_LIST_SUCCESS = "GET_IMAGE_LIST_SUCCESS"
export const GET_IMAGE_LIST_FAIL = "GET_IMAGE_LIST_FAIL"

